### PR TITLE
Include parameter class & improve plotting

### PR DESCRIPTION
**Pull request by jontycarruthersphe**
### **Parameter class**

- The parameter class makes it simpler to specify the parameters included in the inference, their prior distributions and whether they should be sampled on a log-scale. The prior distribution can be chosen from those listed in utilR/distn.py. Because of this, the beta distribution has also been included in utilR/distn.py as this can be helpful when inferring probabilities.

- A function to create the loss object (e.g. SquareLoss) has been included that makes use of the parameter class.  This avoids the need to specify target_param and target_state as these will be determined from the list of parameters provided. It also means that initial guesses for each parameter (theta) no longer need to be specified. This makes sense since these initial guesses weren't being used anyway.   

### **Improved plotting**

-  In plot_pointwise_predictions, it is now possible to plot the solutions for specific states.

- In plot_posterior_histograms and plot_scatter, it is now possible to create posterior histograms and pairs plots for specific parameters.

### CODE REVIEW

**Comment by twomagpi** [comment]
Hi Jonty,
Looks interesting. could you add some correctness-of-function tests to the PR so that we can automatically check that the class is behaving as expected?

many thanks

Tom

**Comment by jontycarruthersphe** [comment]
Hi Tom,

Just to check, does this need to resemble a short example, similar to the tests in pygom/tests?

Thanks,
Jonty

**Comment by jontycarruthersphe** [comment]
I've added some tests that are similar to those for the existing estimation methods. I have also updated the default covariance matrix for the perturbation kernel, it now uses an optimal local covariance matrix.

**Comment by twomagpi** [comment]
Now merged into 0.1.7

**Pull request closed without merging**
